### ISSUE TITLE
Elementary Icons

### ISSUE THREAD

**Issue by naaando** [btd1337/elementary-script#2]
## Hi,
I was taking a look in the script, It seems that it download elementary-icon, **move** it to /usr/share/icons, when a user runs it again (to update icons for example), it do the same thing, would be nice to git pull the icons to reduce bandwidth usage(and script time) by **copying** instead of **moving** or giving a **pull** on **/usr/share/icons/elementary-full-icon-theme** itself.

**Comment by btd1337** [comment]
I don't understand your idea. Can you explain it better?

**Comment by naaando** [comment]
I was talking about the icons being update instead of being downloaded again every time the script is run, but I don't know if it's supposed to be run more than once.

**Comment by btd1337** [comment]
Thank you for your feedback. This feature was implemented in this commit https://github.com/btd1337/elementary-script/commit/db608838007c22abc4d7d80d6e30cd20ddfd62bd
