### ISSUE TITLE
Install Enable Plank magnifying effect

### ISSUE THREAD

**Issue by Tutmos** [btd1337/elementary-script#3]
Plank magnifying effect is not working any more with the last update. (plank 0.11.3 )

**Comment by btd1337** [comment]
Any Idea?

**Comment by Tutmos** [comment]
Nope, if you wish you can remove the part for magnifying Plank.
This is because of Apple, and I think it is not a bug.

**Comment by btd1337** [comment]
Fix in https://github.com/btd1337/elementary-script/commit/93a29f90ac8715df1df12317e70bdbcbbe22c17b
